name: Bug report
about: Report incorrect behavior in prediction market engine or settlement rules
labels: bug

body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Market / Oracle context
      description: Include market type, token mint, and snapshot details if available
